site:
  name: Spring AI Alibaba
  site: 'https://java2ai.com'
  base: '/'
  trailingSlash: 'always'
  websiteGithubUrl: 'https://github.com/springaialibaba/spring-ai-alibaba-website/blob/main'
  githubUrl: 'https://github.com/springaialibaba/spring-ai-alibaba-website'
  logoUrl: "/saa_logo.png"
  downloadEbooks: "https://developer.aliyun.com/ebook/7565"
analytics:
  vendors:
    googleAnalytics:
      id: G-NP3B57ZGEF # or "G-XXXXXXXXXX"
    baiduAnalytics:
      id: 0b8bbee27b5404c869dded46a59bdc8d
      verification: code-wzq5sw7io3
    aesAnalytics:
      pid: b3kPns
    clarityAlalytics:
      id: l4jzj6wbhh
# Default SEO metadata
metadata:
  title:
    default: AstroWind
    template: '%s â€” AstroWind'
  description: "ğŸš€ Suitable for Startups, Small Business, Sass Websites, Professional Portfolios, Marketing Websites, Landing Pages & Blogs."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: AstroWind
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image
ui:
  colors:
    # ä¸»æŒ‰é’®é¢œè‰²ï¼Œä¸€èˆ¬ä¸ºä¸»è‰²ä¸­é—´çš„é¢œè‰²
    primary: "#5DC07E" # green-08
    # æ¬¡æŒ‰é’®çš„é¢œè‰²ï¼Œä¸€èˆ¬ä¸ºç°è‰²è°ƒæœ€æµ…é¢œè‰²
    secondary: "#F6F8F8" #moss-01
    # å¼ºè°ƒè‰²ã€‚"Header"ä¸­çš„è”ç³»æˆ‘ä»¬
    accent: "#418B47" #green-10
    # ä¸­æ€§è‰²ã€‚ä½œä¸ºå¤§æ ‡é¢˜çš„å­—ä½“é¢œè‰²
    neutral: "#0C1D0D" #green-14
    # åŸºç¡€è‰²ï¼Œç”¨åšé¦–é¡µçš„èƒŒæ™¯è‰²1
    base-100: "#F6F8F8" # moss-01
    # ä¿¡æ¯é¢œè‰²ã€‚Headlineçš„ä¸Šæ–¹å°å­—, Fotterå•†æ ‡å­—ä½“é¢œè‰²
    info: "#666963" #gray-10
    # æˆåŠŸã€‚ Headerçš„åˆ†å‰²ç¬¦ã€ä¸»è¦ç‰¹æ€§ä¸­çš„åˆ†å‰²ç¬¦ã€companiesfeedbackä¸­çš„isGrayçš„èƒŒæ™¯é¢œè‰²
    success: "#7E9B99" #moss-08
    # è­¦å‘Šã€‚headerä¸­çš„toggle-trigger-atcé¢œè‰²
    warning: "#597371" #moss-10
    # é”™è¯¯ã€‚æœç´¢ç­‰ç»„ä»¶çš„bgcolor
    error: "#EBEFEF" #moss-02
    # é™éŸ³ companiesfeedbackä¸­çš„isLightçš„èƒŒæ™¯é¢œè‰²
    muted: "#D3EDD5" #green-03
    # æœç´¢/è¯­è¨€åˆ‡æ¢ç»„ä»¶çš„æ–‡å­—é¢œè‰²
    link: "#DDE4E4" #moss-03
